import { booleanFormatter } from "./services/formatters.js";

export const sources = [
  {
    sourcePath: "data/UKBB_autosomal_mCA_92005app_clean.txt",
    table: "sample",
    description: "UKBB blood autosomal mCAs",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "UKBB_blood_autosomal_mCAs" },
      { sourceName: "sample_id", name: "sampleId" },
      { sourceName: "computed_gender", name: "computedGender" },
      { sourceName: "chrom", name: "chromosome" },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
      { sourceName: "length", name: "length" },
      { sourceName: "p_arm", name: "pArm" },
      { sourceName: "q_arm", name: "qArm" },
      { sourceName: "n_sites", name: "nSites" },
      { sourceName: "n_hets", name: "nHets" },
      { sourceName: "n50_hets", name: "n50Hets" },
      { sourceName: "bdev", name: "bdev" },
      { sourceName: "bdev_se", name: "bdevSe" },
      { sourceName: "rel_cov", name: "relCov" },
      { sourceName: "rel_cov_se", name: "relCovSe" },
      { sourceName: "lod_lrr_baf", name: "lodLrrBaf" },
      { sourceName: "lod_baf_phase", name: "lodBafPhase" },
      { sourceName: "n_flips", name: "nFlips" },
      { sourceName: "baf_conc", name: "bafConc" },
      { sourceName: "lod_baf_conc", name: "lodBafConc" },
      { sourceName: "type", name: "type" },
      { sourceName: "cf", name: "cf" },
    ],
  },
  {
    sourcePath: "data/UKBB_V2/UKBB_mLOX_mCA_92005app_clean.txt",
    table: "sample",
    description: "/UKBB_blood_mLOX",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "UKBB_blood_mLOX" },
      { sourceName: "sample_id", name: "sampleId" },
      { sourceName: "computed_gender", name: "computedGender" },
      { sourceName: "chrom", name: "chromosome" },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
      { sourceName: "length", name: "length" },
      { sourceName: "p_arm", name: "pArm" },
      { sourceName: "q_arm", name: "qArm" },
      { sourceName: "n_sites", name: "nSites" },
      { sourceName: "n_hets", name: "nHets" },
      { sourceName: "n50_hets", name: "n50Hets" },
      { sourceName: "bdev", name: "bdev" },
      { sourceName: "bdev_se", name: "bdevSe" },
      { sourceName: "rel_cov", name: "relCov" },
      { sourceName: "rel_cov_se", name: "relCovSe" },
      { sourceName: "lod_lrr_baf", name: "lodLrrBaf" },
      { sourceName: "lod_baf_phase", name: "lodBafPhase" },
      { sourceName: "n_flips", name: "nFlips" },
      { sourceName: "baf_conc", name: "bafConc" },
      { sourceName: "lod_baf_conc", name: "lodBafConc" },
      { sourceName: "type-FINAL", name: "typeFinal" },
      { sourceName: "cf_FINAL", name: "cf" },
      { sourceName: "call_rate", name: "callRate" },
      { sourceName: "baf_auto", name: "bafAuto" },
    ],
  },
  {
    sourcePath: "data/UKBB_V2/UKBB_mLOY_mCA_92005app_clean.txt",
    table: "sample",
    description: "UKBB blood mLOY",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "UKBB_blood_mLOY" },
      { sourceName: "sample_id", name: "sampleId" },
      { sourceName: "computed_gender", name: "computedGender" },
      { sourceName: "chrom", name: "chromosome" },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
      { sourceName: "length", name: "length" },
      { sourceName: "p_arm", name: "pArm" },
      { sourceName: "q_arm", name: "qArm" },
      { sourceName: "n_sites", name: "nSites" },
      { sourceName: "n_hets", name: "nHets" },
      { sourceName: "n50_hets", name: "n50Hets" },
      { sourceName: "bdev", name: "bdev" },
      { sourceName: "bdev_se", name: "bdevSe" },
      { sourceName: "rel_cov", name: "relCov" },
      { sourceName: "rel_cov_se", name: "relCovSe" },
      { sourceName: "lod_lrr_baf", name: "lodLrrBaf" },
      { sourceName: "lod_baf_phase", name: "lodBafPhase" },
      { sourceName: "n_flips", name: "nFlips" },
      { sourceName: "baf_conc", name: "bafConc" },
      { sourceName: "lod_baf_conc", name: "lodBafConc" },
      { sourceName: "type_FINAL", name: "typeFinal" },
      { sourceName: "cf_FINAL", name: "cf" },
      { sourceName: "call_rate", name: "callRate" },
      { sourceName: "baf_auto", name: "bafAuto" },
    ],
  },
  {
    sourcePath: "data/UKBB_V2/UKBB_denominator_92005app_clean.txt",
    table: "sample",
    description: "UKBB denominator",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "UKBB_denominator" },
      { sourceName: "Sample_ID", name: "sampleId" },
      { sourceName: "age", name: "age" },
      { sourceName: "sex", name: "sex" },
      { sourceName: "smoke_NFC", name: "smokeNFC" },
      { sourceName: "#SNPs", name: "numSNPs" },
      { sourceName: "GD1", name: "GD1" },
      { sourceName: "GD2", name: "GD2" },
      { sourceName: "GD3", name: "GD3" },
      { sourceName: "GD4", name: "GD4" },
      { sourceName: "Percent_f", name: "PercentF" },
      { sourceName: "Percent_e", name: "PercentE" },
      { sourceName: "Percent_a", name: "PercentA" },
      { sourceName: "PopID", name: "PopID" },
      { sourceName: "dna_source", name: "dnaSource" },
      { sourceName: "array", name: "array" },
      { sourceName: "prior_cancer", name: "priorCancer" },
      { sourceName: "incident_cancer_hem", name: "incidentCancerHem" },
      { sourceName: "incident_cancer_myeloid", name: "incidentCancerMyeloid" },
      { sourceName: "cf_FINAL", name: "cf" },
      { sourceName: "call_rate", name: "callRate" },
      { sourceName: "baf_auto", name: "bafAuto" },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
    ],
  },
];

export default sources;
