import { booleanFormatter } from "./services/formatters.js";

export const sources = [
  {
    sourcePath: "data/PLCO_GSA_blood_autosomal_mCAs.txt",
    table: "sample",
    description: "PLCO GSA blood autosomal mCAs",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "PLCO_GSA_blood_autosomal_mCAs" },
      { sourceName: "sample_id", name: "sampleId" },
      { sourceName: "computed_gender", name: "computedGender" },
      { sourceName: "chrom", name: "chromosome" },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
      { sourceName: "length", name: "length" },
      { sourceName: "p_arm", name: "pArm" },
      { sourceName: "q_arm", name: "qArm" },
      { sourceName: "n_sites", name: "nSites" },
      { sourceName: "n_hets", name: "nHets" },
      { sourceName: "n50_hets", name: "n50Hets" },
      { sourceName: "bdev", name: "bdev" },
      { sourceName: "bdev_se", name: "bdevSe" },
      { sourceName: "rel_cov", name: "relCov" },
      { sourceName: "rel_cov_se", name: "relCovSe" },
      { sourceName: "lod_lrr_baf", name: "lodLrrBaf" },
      { sourceName: "lod_baf_phase", name: "lodBafPhase" },
      { sourceName: "n_flips", name: "nFlips" },
      { sourceName: "baf_conc", name: "bafConc" },
      { sourceName: "lod_baf_conc", name: "lodBafConc" },
      { sourceName: "type", name: "type" },
      { sourceName: "cf", name: "cf" },
      { sourceName: "group", name: "group" },
      { sourceName: "SR_Subject_ID", name: "srSubjectId" },
      { sourceName: "LIMS_Individual_ID", name: "limsIndividualId" },
      { sourceName: "Project", name: "project" },
      { sourceName: "LIMSSample_ID", name: "limsSampleId" },
      { sourceName: "Expected_Sex", name: "expectedSex" },
      { sourceName: "Predicted_Sex_FINAL", name: "predictedSex" },
      { sourceName: "SexMatch_FINAL", name: "sexMatch", formatter: booleanFormatter("Y", "N") },
      { sourceName: "AFR", name: "afr" },
      { sourceName: "EUR", name: "eur" },
      { sourceName: "ASN", name: "asn" },
      { sourceName: "Ancestry", name: "ancestry" },
      { sourceName: "Call_Rate_1", name: "callRate1" },
      { sourceName: "Sex Discordant_FINAL", name: "sexDiscordant", formatter: booleanFormatter("TRUE", "FALSE") },
      { sourceName: "Expected Replicate Discordance", name: "expectedReplicateDiscordance", formatter: booleanFormatter("TRUE", "FALSE") },
      { sourceName: "Unexpected Replicate", name: "unexpectedReplicate", formatter: booleanFormatter("TRUE", "FALSE") },
      { sourceName: "MoChA_autosomal_Final", name: "mochaAutosomal", formatter: booleanFormatter("Y", "N") },
      { sourceName: "plco_id", name: "plcoId" },
      { sourceName: "blood_buccal", name: "bloodBuccal" },
      { sourceName: "call_rate", name: "callRate" },
      { sourceName: "baf_auto", name: "bafAuto" },
    ],
  },
  {
    sourcePath: "data/PLCO_GSA_blood_denominator.txt",
    table: "sample",
    description: "PLCO GSA blood denominator",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "PLCO_GSA_blood_denominator" },
      { sourceName: "Sample_ID", name: "sampleId" },
      { sourceName: "group", name: "group" },
      { sourceName: "SR_Subject_ID", name: "srSubjectId" },
      { sourceName: "LIMS_Individual_ID", name: "limsIndividualId" },
      { sourceName: "Project", name: "project" },
      { sourceName: "LIMSSample_ID", name: "limsSampleId" },
      { sourceName: "Expected_Sex", name: "expectedSex" },
      { sourceName: "Predicted_Sex_FINAL", name: "predictedSex" },
      { sourceName: "SexMatch_FINAL", name: "sexMatch", formatter: booleanFormatter("Y", "N") },
      { sourceName: "AFR", name: "afr" },
      { sourceName: "EUR", name: "eur" },
      { sourceName: "ASN", name: "asn" },
      { sourceName: "Ancestry", name: "ancestry" },
      { sourceName: "Call_Rate_1", name: "callRate1" },
      { sourceName: "Sex Discordant_FINAL", name: "sexDiscordant", formatter: booleanFormatter("TRUE", "FALSE") },
      { sourceName: "Expected Replicate Discordance", name: "expectedReplicateDiscordance", formatter: booleanFormatter("TRUE", "FALSE") },
      { sourceName: "Unexpected Replicate", name: "unexpectedReplicate", formatter: booleanFormatter("TRUE", "FALSE") },
      { sourceName: "MoChA_autosomal_Final", name: "mochaAutosomal", formatter: booleanFormatter("Y", "N") },
      { sourceName: "plco_id", name: "plcoId" },
      { sourceName: "blood_buccal", name: "bloodBuccal" },
      { sourceName: "call_rate", name: "callRate" },
      { sourceName: "baf_auto", name: "bafAuto" },
    ],
  },
  {
    sourcePath: "data/PLCO_GSA_blood_mLOX.txt",
    table: "sample",
    description: "PLCO_GSA_blood_mLOX",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "PLCO_GSA_blood_mLOX" },
      { sourceName: "sample_id", name: "sampleId" },
      { sourceName: "computed_gender", name: "computedGender" },
      { sourceName: "chrom", name: "chromosome" },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
      { sourceName: "length", name: "length" },
      { sourceName: "p_arm", name: "pArm" },
      { sourceName: "q_arm", name: "qArm" },
      { sourceName: "n_sites", name: "nSites" },
      { sourceName: "n_hets", name: "nHets" },
      { sourceName: "n50_hets", name: "n50Hets" },
      { sourceName: "bdev", name: "bdev" },
      { sourceName: "bdev_se", name: "bdevSe" },
      { sourceName: "rel_cov", name: "relCov" },
      { sourceName: "rel_cov_se", name: "relCovSe" },
      { sourceName: "lod_lrr_baf", name: "lodLrrBaf" },
      { sourceName: "lod_baf_phase", name: "lodBafPhase" },
      { sourceName: "n_flips", name: "nFlips" },
      { sourceName: "baf_conc", name: "bafConc" },
      { sourceName: "lod_baf_conc", name: "lodBafConc" },
      { sourceName: "type_FINAL", name: "type" },
      { sourceName: "cf_FINAL", name: "cf" },
      { sourceName: "group", name: "group" },
      { sourceName: "SR_Subject_ID", name: "srSubjectId" },
      { sourceName: "LIMS_Individual_ID", name: "limsIndividualId" },
      { sourceName: "Project", name: "project" },
      { sourceName: "LIMSSample_ID", name: "limsSampleId" },
      { sourceName: "Expected_Sex", name: "expectedSex" },
      { sourceName: "Predicted_Sex_FINAL", name: "predictedSex" },
      { sourceName: "SexMatch_FINAL", name: "sexMatch", formatter: booleanFormatter("Y", "N") },
      { sourceName: "AFR", name: "afr" },
      { sourceName: "EUR", name: "eur" },
      { sourceName: "ASN", name: "asn" },
      { sourceName: "Ancestry", name: "ancestry" },
      { sourceName: "Call_Rate_1", name: "callRate1" },
      { sourceName: "Sex Discordant_FINAL", name: "sexDiscordant", formatter: booleanFormatter("TRUE", "FALSE") },
      { sourceName: "Expected Replicate Discordance", name: "expectedReplicateDiscordance", formatter: booleanFormatter("TRUE", "FALSE") },
      { sourceName: "Unexpected Replicate", name: "unexpectedReplicate", formatter: booleanFormatter("TRUE", "FALSE") },
      { sourceName: "MoChA_autosomal_Final", name: "mochaAutosomal", formatter: booleanFormatter("Y", "N") },
      { sourceName: "plco_id", name: "plcoId" },
      { sourceName: "blood_buccal", name: "bloodBuccal" },
      { sourceName: "call_rate", name: "callRate" },
      { sourceName: "baf_auto", name: "bafAuto" },
    ],
  },
  {
    sourcePath: "data/PLCO_GSA_blood_mLOY.txt",
    table: "sample",
    description: "PLCO GSA blood mLOY",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "PLCO_GSA_blood_mLOY" },
      { sourceName: "sample_id", name: "sampleId" },
      { sourceName: "computed_gender", name: "computedGender" },
      { sourceName: "chrom", name: "chromosome" },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
      { sourceName: "length", name: "length" },
      { sourceName: "p_arm", name: "pArm" },
      { sourceName: "q_arm", name: "qArm" },
      { sourceName: "n_sites", name: "nSites" },
      { sourceName: "n_hets", name: "nHets" },
      { sourceName: "n50_hets", name: "n50Hets" },
      { sourceName: "bdev", name: "bdev" },
      { sourceName: "bdev_se", name: "bdevSe" },
      { sourceName: "rel_cov", name: "relCov" },
      { sourceName: "rel_cov_se", name: "relCovSe" },
      { sourceName: "lod_lrr_baf", name: "lodLrrBaf" },
      { sourceName: "lod_baf_phase", name: "lodBafPhase" },
      { sourceName: "n_flips", name: "nFlips" },
      { sourceName: "baf_conc", name: "bafConc" },
      { sourceName: "lod_baf_conc", name: "lodBafConc" },
      { sourceName: "type_FAINL", name: "type" },
      { sourceName: "cf_FINAL", name: "cf" },
      { sourceName: "group", name: "group" },
      { sourceName: "SR_Subject_ID", name: "srSubjectId" },
      { sourceName: "LIMS_Individual_ID", name: "limsIndividualId" },
      { sourceName: "Project", name: "project" },
      { sourceName: "LIMSSample_ID", name: "limsSampleId" },
      { sourceName: "Expected_Sex", name: "expectedSex" },
      { sourceName: "Predicted_Sex_FINAL", name: "predictedSex" },
      { sourceName: "SexMatch_FINAL", name: "sexMatch", formatter: booleanFormatter("Y", "N") },
      { sourceName: "AFR", name: "afr" },
      { sourceName: "EUR", name: "eur" },
      { sourceName: "ASN", name: "asn" },
      { sourceName: "Ancestry", name: "ancestry" },
      { sourceName: "Call_Rate_1", name: "callRate1" },
      { sourceName: "Sex Discordant_FINAL", name: "sexDiscordant", formatter: booleanFormatter("TRUE", "FALSE") },
      { sourceName: "Expected Replicate Discordance", name: "expectedReplicateDiscordance", formatter: booleanFormatter("TRUE", "FALSE") },
      { sourceName: "Unexpected Replicate", name: "unexpectedReplicate", formatter: booleanFormatter("TRUE", "FALSE") },
      { sourceName: "MoChA_autosomal_Final", name: "mochaAutosomal", formatter: booleanFormatter("Y", "N") },
      { sourceName: "plco_id", name: "plcoId" },
      { sourceName: "blood_buccal", name: "bloodBuccal" },
      { sourceName: "call_rate", name: "callRate" },
      { sourceName: "baf_auto", name: "bafAuto" },
    ],
  },
];

export default sources;
