import { ageRangeMaxFormatter, ageRangeMinFormatter, booleanFormatter, chromosomeFormatter, platformFormatter } from "./services/formatters.js";

const platformMap = {
  "Illumina OmniExpress / OmniExpress Exome family (sample batch unspecified)": "OMNI Express",
};

const topmedSmokeMap = {
  1: "3",
};

export const sources = [
  {
    sourcePath: "data/raw_v3_20240916/PLCO_GSA_blood_autosomal_mCAs.txt",
    table: "sample",
    description: "PLCO GSA blood autosomal mCAs",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "PLCO_GSA_blood_autosomal_mCAs" },
      { sourceName: "sample_id", name: "sampleIdOld" },
      { sourceName: "Sample_ID", name: "sampleIdOld2" },
      { sourceName: "computed_gender", name: "computedGender" },
      { sourceName: "chrom", name: "chromosome", formatter: chromosomeFormatter() },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
      { sourceName: "length", name: "length" },
      { sourceName: "p_arm", name: "pArm" },
      { sourceName: "q_arm", name: "qArm" },
      { sourceName: "n_sites", name: "nSites" },
      { sourceName: "n_hets", name: "nHets" },
      { sourceName: "n50_hets", name: "n50Hets" },
      { sourceName: "bdev", name: "bdev" },
      { sourceName: "bdev_se", name: "bdevSe" },
      { sourceName: "rel_cov", name: "relCov" },
      { sourceName: "rel_cov_se", name: "relCovSe" },
      { sourceName: "lod_lrr_baf", name: "lodLrrBaf" },
      { sourceName: "lod_baf_phase", name: "lodBafPhase" },
      { sourceName: "n_flips", name: "nFlips" },
      { sourceName: "baf_conc", name: "bafConc" },
      { sourceName: "lod_baf_conc", name: "lodBafConc" },
      { sourceName: "type", name: "type" },
      { sourceName: "cf", name: "cf" },
      { sourceName: "group", name: "group" },
      { sourceName: "SR_Subject_ID", name: "srSubjectId" },
      { sourceName: "LIMS_Individual_ID", name: "limsIndividualId" },
      { sourceName: "Project", name: "project" },
      { sourceName: "LIMSSample_ID", name: "limsSampleId" },
      { sourceName: "Expected_Sex", name: "expectedSex" },
      { sourceName: "Predicted_Sex_FINAL", name: "predictedSex" },
      { sourceName: "SexMatch_FINAL", name: "sexMatch", formatter: booleanFormatter("Y", "N") },
      { sourceName: "AFR", name: "afr" },
      { sourceName: "EUR", name: "eur" },
      { sourceName: "ASN", name: "asn" },
      { sourceName: "Ancestry", name: "ancestry" },
      { sourceName: "Call_Rate_1", name: "callRate1" },
      { sourceName: "Sex Discordant_FINAL", name: "sexDiscordant", formatter: booleanFormatter("TRUE", "FALSE") },
      {
        sourceName: "Expected Replicate Discordance",
        name: "expectedReplicateDiscordance",
        formatter: booleanFormatter("TRUE", "FALSE"),
      },
      { sourceName: "Unexpected Replicate", name: "unexpectedReplicate", formatter: booleanFormatter("TRUE", "FALSE") },
      { sourceName: "MoChA_autosomal_Final", name: "mochaAutosomal", formatter: booleanFormatter("Y", "N") },
      { sourceName: "plco_id", name: "sampleId" },
      { sourceName: "blood_buccal", name: "bloodBuccal" },
      { sourceName: "call_rate", name: "callRate" },
      { sourceName: "baf_auto", name: "bafAuto" },
    ],
  },
  {
    sourcePath: "data/raw_v3_20240916/PLCO_denominator_clean.txt",
    table: "sample",
    description: "PLCO GSA blood denominator",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "PLCO_denominator" },
      { sourceName: "Sample_ID", name: "sampleId" },
      { sourceName: "age", name: "age" },
      { sourceName: "sex", name: "sex" },
      { sourceName: "smoke_NFC", name: "smokeNFC" },
      { sourceName: "NumSNPs", name: "numSNPs" },
      { sourceName: "GD1", name: "GD1" },
      { sourceName: "GD2", name: "GD2" },
      { sourceName: "GD3", name: "GD3" },
      { sourceName: "GD4", name: "GD4" },
      { sourceName: "Percent_f", name: "PercentF" },
      { sourceName: "Percent_e", name: "PercentE" },
      { sourceName: "Percent_a", name: "PercentA" },
      { sourceName: "PopID", name: "PopID" },
      { sourceName: "dna_source", name: "dnaSource" },
      { sourceName: "array", name: "array" },
      { sourceName: "prior_cancer", name: "priorCancer" },
      { sourceName: "incident_cancer_hem", name: "incidentCancerHem" },
      { sourceName: "incident_cancer_myeloid", name: "incidentCancerMyeloid" },
      { sourceName: "incident_cancer_lymphoid", name: "incidentCancerLymphoid" },
      { sourceName: "cf_FINAL", name: "cf" },
      { sourceName: "call_rate", name: "callRate" },
      { sourceName: "baf_auto", name: "bafAuto" },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
    ],
  },
  {
    sourcePath: "data/raw_v3_20240916/PLCO_GSA_blood_mLOX.txt",
    table: "sample",
    description: "PLCO_GSA_blood_mLOX",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "PLCO_GSA_blood_mLOX" },
      { sourceName: "sample_id", name: "sampleIdOld" },
      { sourceName: "Sample_ID", name: "sampleIdOld2" },
      { sourceName: "computed_gender", name: "computedGender" },
      { sourceName: "chrom", name: "chromosome", formatter: chromosomeFormatter() },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
      { sourceName: "length", name: "length" },
      { sourceName: "p_arm", name: "pArm" },
      { sourceName: "q_arm", name: "qArm" },
      { sourceName: "n_sites", name: "nSites" },
      { sourceName: "n_hets", name: "nHets" },
      { sourceName: "n50_hets", name: "n50Hets" },
      { sourceName: "bdev", name: "bdev" },
      { sourceName: "bdev_se", name: "bdevSe" },
      { sourceName: "rel_cov", name: "relCov" },
      { sourceName: "rel_cov_se", name: "relCovSe" },
      { sourceName: "lod_lrr_baf", name: "lodLrrBaf" },
      { sourceName: "lod_baf_phase", name: "lodBafPhase" },
      { sourceName: "n_flips", name: "nFlips" },
      { sourceName: "baf_conc", name: "bafConc" },
      { sourceName: "lod_baf_conc", name: "lodBafConc" },
      { sourceName: "type_FINAL", name: "type" },
      { sourceName: "cf_FINAL", name: "cf" },
      { sourceName: "group", name: "group" },
      { sourceName: "SR_Subject_ID", name: "srSubjectId" },
      { sourceName: "LIMS_Individual_ID", name: "limsIndividualId" },
      { sourceName: "Project", name: "project" },
      { sourceName: "LIMSSample_ID", name: "limsSampleId" },
      { sourceName: "Expected_Sex", name: "expectedSex" },
      { sourceName: "Predicted_Sex_FINAL", name: "predictedSex" },
      { sourceName: "SexMatch_FINAL", name: "sexMatch", formatter: booleanFormatter("Y", "N") },
      { sourceName: "AFR", name: "afr" },
      { sourceName: "EUR", name: "eur" },
      { sourceName: "ASN", name: "asn" },
      { sourceName: "Ancestry", name: "ancestry" },
      { sourceName: "Call_Rate_1", name: "callRate1" },
      { sourceName: "Sex Discordant_FINAL", name: "sexDiscordant", formatter: booleanFormatter("TRUE", "FALSE") },
      {
        sourceName: "Expected Replicate Discordance",
        name: "expectedReplicateDiscordance",
        formatter: booleanFormatter("TRUE", "FALSE"),
      },
      { sourceName: "Unexpected Replicate", name: "unexpectedReplicate", formatter: booleanFormatter("TRUE", "FALSE") },
      { sourceName: "MoChA_autosomal_Final", name: "mochaAutosomal", formatter: booleanFormatter("Y", "N") },
      { sourceName: "plco_id", name: "sampleId" },
      { sourceName: "blood_buccal", name: "bloodBuccal" },
      { sourceName: "call_rate", name: "callRate" },
      { sourceName: "baf_auto", name: "bafAuto" },
    ],
  },
  {
    sourcePath: "data/raw_v3_20240916/PLCO_GSA_blood_mLOY.txt",
    table: "sample",
    description: "PLCO GSA blood mLOY",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "PLCO_GSA_blood_mLOY" },
      { sourceName: "sample_id", name: "sampleIdOld" },
      { sourceName: "Sample_ID", name: "sampleIdOld2" },
      { sourceName: "computed_gender", name: "computedGender" },
      { sourceName: "chrom", name: "chromosome", formatter: chromosomeFormatter() },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
      { sourceName: "length", name: "length" },
      { sourceName: "p_arm", name: "pArm" },
      { sourceName: "q_arm", name: "qArm" },
      { sourceName: "n_sites", name: "nSites" },
      { sourceName: "n_hets", name: "nHets" },
      { sourceName: "n50_hets", name: "n50Hets" },
      { sourceName: "bdev", name: "bdev" },
      { sourceName: "bdev_se", name: "bdevSe" },
      { sourceName: "rel_cov", name: "relCov" },
      { sourceName: "rel_cov_se", name: "relCovSe" },
      { sourceName: "lod_lrr_baf", name: "lodLrrBaf" },
      { sourceName: "lod_baf_phase", name: "lodBafPhase" },
      { sourceName: "n_flips", name: "nFlips" },
      { sourceName: "baf_conc", name: "bafConc" },
      { sourceName: "lod_baf_conc", name: "lodBafConc" },
      { sourceName: "type_FINAL", name: "type" },
      { sourceName: "cf_FINAL", name: "cf" },
      { sourceName: "group", name: "group" },
      { sourceName: "SR_Subject_ID", name: "srSubjectId" },
      { sourceName: "LIMS_Individual_ID", name: "limsIndividualId" },
      { sourceName: "Project", name: "project" },
      { sourceName: "LIMSSample_ID", name: "limsSampleId" },
      { sourceName: "Expected_Sex", name: "expectedSex" },
      { sourceName: "Predicted_Sex_FINAL", name: "predictedSex" },
      { sourceName: "SexMatch_FINAL", name: "sexMatch", formatter: booleanFormatter("Y", "N") },
      { sourceName: "AFR", name: "afr" },
      { sourceName: "EUR", name: "eur" },
      { sourceName: "ASN", name: "asn" },
      { sourceName: "Ancestry", name: "ancestry" },
      { sourceName: "Call_Rate_1", name: "callRate1" },
      { sourceName: "Sex Discordant_FINAL", name: "sexDiscordant", formatter: booleanFormatter("TRUE", "FALSE") },
      {
        sourceName: "Expected Replicate Discordance",
        name: "expectedReplicateDiscordance",
        formatter: booleanFormatter("TRUE", "FALSE"),
      },
      { sourceName: "Unexpected Replicate", name: "unexpectedReplicate", formatter: booleanFormatter("TRUE", "FALSE") },
      { sourceName: "MoChA_autosomal_Final", name: "mochaAutosomal", formatter: booleanFormatter("Y", "N") },
      { sourceName: "plco_id", name: "sampleId" },
      { sourceName: "blood_buccal", name: "bloodBuccal" },
      { sourceName: "call_rate", name: "callRate" },
      { sourceName: "baf_auto", name: "bafAuto" },
    ],
  },

  {
    sourcePath: "data/raw_v3_20240916/UKBB_autosomal_mCA_92005app_clean.txt",
    table: "sample",
    description: "UKBB blood autosomal mCAs",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "UKBB_blood_autosomal_mCAs" },
      { sourceName: "sample_id", name: "sampleId" },
      { sourceName: "computed_gender", name: "computedGender" },
      { sourceName: "chrom", name: "chromosome", formatter: chromosomeFormatter() },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
      { sourceName: "length", name: "length" },
      { sourceName: "p_arm", name: "pArm" },
      { sourceName: "q_arm", name: "qArm" },
      { sourceName: "n_sites", name: "nSites" },
      { sourceName: "n_hets", name: "nHets" },
      { sourceName: "n50_hets", name: "n50Hets" },
      { sourceName: "bdev", name: "bdev" },
      { sourceName: "bdev_se", name: "bdevSe" },
      { sourceName: "rel_cov", name: "relCov" },
      { sourceName: "rel_cov_se", name: "relCovSe" },
      { sourceName: "lod_lrr_baf", name: "lodLrrBaf" },
      { sourceName: "lod_baf_phase", name: "lodBafPhase" },
      { sourceName: "n_flips", name: "nFlips" },
      { sourceName: "baf_conc", name: "bafConc" },
      { sourceName: "lod_baf_conc", name: "lodBafConc" },
      { sourceName: "type", name: "type" },
      { sourceName: "cf", name: "cf" },
    ],
  },
  {
    sourcePath: "data/raw_v3_20240916/UKBB_mLOX_mCA_92005app_clean.txt",
    table: "sample",
    description: "/UKBB_blood_mLOX",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "UKBB_blood_mLOX" },
      { sourceName: "sample_id", name: "sampleId" },
      { sourceName: "computed_gender", name: "computedGender" },
      { sourceName: "chrom", name: "chromosome", formatter: chromosomeFormatter() },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
      { sourceName: "length", name: "length" },
      { sourceName: "p_arm", name: "pArm" },
      { sourceName: "q_arm", name: "qArm" },
      { sourceName: "n_sites", name: "nSites" },
      { sourceName: "n_hets", name: "nHets" },
      { sourceName: "n50_hets", name: "n50Hets" },
      { sourceName: "bdev", name: "bdev" },
      { sourceName: "bdev_se", name: "bdevSe" },
      { sourceName: "rel_cov", name: "relCov" },
      { sourceName: "rel_cov_se", name: "relCovSe" },
      { sourceName: "lod_lrr_baf", name: "lodLrrBaf" },
      { sourceName: "lod_baf_phase", name: "lodBafPhase" },
      { sourceName: "n_flips", name: "nFlips" },
      { sourceName: "baf_conc", name: "bafConc" },
      { sourceName: "lod_baf_conc", name: "lodBafConc" },
      { sourceName: "type_FINAL", name: "type" },
      { sourceName: "cf_FINAL", name: "cf" },
      { sourceName: "call_rate", name: "callRate" },
      { sourceName: "baf_auto", name: "bafAuto" },
    ],
  },
  {
    sourcePath: "data/raw_v3_20240916/UKBB_mLOY_mCA_92005app_clean.txt",
    table: "sample",
    description: "UKBB blood mLOY",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "UKBB_blood_mLOY" },
      { sourceName: "sample_id", name: "sampleId" },
      { sourceName: "computed_gender", name: "computedGender" },
      { sourceName: "chrom", name: "chromosome", formatter: chromosomeFormatter() },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
      { sourceName: "length", name: "length" },
      { sourceName: "p_arm", name: "pArm" },
      { sourceName: "q_arm", name: "qArm" },
      { sourceName: "n_sites", name: "nSites" },
      { sourceName: "n_hets", name: "nHets" },
      { sourceName: "n50_hets", name: "n50Hets" },
      { sourceName: "bdev", name: "bdev" },
      { sourceName: "bdev_se", name: "bdevSe" },
      { sourceName: "rel_cov", name: "relCov" },
      { sourceName: "rel_cov_se", name: "relCovSe" },
      { sourceName: "lod_lrr_baf", name: "lodLrrBaf" },
      { sourceName: "lod_baf_phase", name: "lodBafPhase" },
      { sourceName: "n_flips", name: "nFlips" },
      { sourceName: "baf_conc", name: "bafConc" },
      { sourceName: "lod_baf_conc", name: "lodBafConc" },
      { sourceName: "type_FINAL", name: "type" },
      { sourceName: "cf_FINAL", name: "cf" },
      { sourceName: "call_rate", name: "callRate" },
      { sourceName: "baf_auto", name: "bafAuto" },
    ],
  },
  {
    sourcePath: "data/raw_v3_20240916/UKBB_denominator_92005app_clean.txt",
    table: "sample",
    description: "UKBB denominator",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "UKBB_denominator" },
      { sourceName: "Sample_ID", name: "sampleId" },
      { sourceName: "age", name: "age" },
      { sourceName: "sex", name: "sex" },
      { sourceName: "smoke_NFC", name: "smokeNFC" },
      { sourceName: "NumSNPs", name: "numSNPs" },
      { sourceName: "GD1", name: "GD1" },
      { sourceName: "GD2", name: "GD2" },
      { sourceName: "GD3", name: "GD3" },
      { sourceName: "GD4", name: "GD4" },
      { sourceName: "Percent_f", name: "PercentF" },
      { sourceName: "Percent_e", name: "PercentE" },
      { sourceName: "Percent_a", name: "PercentA" },
      { sourceName: "PopID", name: "PopID" },
      { sourceName: "dna_source", name: "dnaSource" },
      { sourceName: "array", name: "array" },
      { sourceName: "prior_cancer", name: "priorCancer" },
      { sourceName: "incident_cancer_hem", name: "incidentCancerHem" },
      { sourceName: "incident_cancer_myeloid", name: "incidentCancerMyeloid" },
      { sourceName: "incident_cancer_lymphoid", name: "incidentCancerLymphoid" },
      { sourceName: "cf_FINAL", name: "cf" },
      { sourceName: "call_rate", name: "callRate" },
      { sourceName: "baf_auto", name: "bafAuto" },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
    ],
  },

// Biovu data

   {
    sourcePath: "data/biovu/BioVU_autosomalmcas_clean_02052025.txt",
    table: "sample",
    description: "BioVU blood autosomal mCAs",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "BioVU_blood_autosomal_mCAs" },
      { sourceName: "sample_id", name: "sampleId" },
      { sourceName: "computed_gender", name: "computedGender" },
      { sourceName: "chrom", name: "chromosome", formatter: chromosomeFormatter() },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
      { sourceName: "length", name: "length" },
      { sourceName: "p_arm", name: "pArm" },
      { sourceName: "q_arm", name: "qArm" },
      { sourceName: "n_sites", name: "nSites" },
      { sourceName: "n_hets", name: "nHets" },
      { sourceName: "n50_hets", name: "n50Hets" },
      { sourceName: "bdev", name: "bdev" },
      { sourceName: "bdev_se", name: "bdevSe" },
      { sourceName: "rel_cov", name: "relCov" },
      { sourceName: "rel_cov_se", name: "relCovSe" },
      { sourceName: "lod_lrr_baf", name: "lodLrrBaf" },
      { sourceName: "lod_baf_phase", name: "lodBafPhase" },
      { sourceName: "n_flips", name: "nFlips" },
      { sourceName: "baf_conc", name: "bafConc" },
      { sourceName: "lod_baf_conc", name: "lodBafConc" },
      { sourceName: "type", name: "type" },
      { sourceName: "cf", name: "cf" },
    ],
  },
  {
    sourcePath: "data/biovu/BioVU_mlox_clean_02052025.txt",
    table: "sample",
    description: "BioVU blood mLOX",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "BioVU_blood_mLOX" },
      { sourceName: "sample_id", name: "sampleId" },
      { sourceName: "computed_gender", name: "computedGender" },
      { sourceName: "chrom", name: "chromosome", formatter: chromosomeFormatter() },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
      { sourceName: "length", name: "length" },
      { sourceName: "p_arm", name: "pArm" },
      { sourceName: "q_arm", name: "qArm" },
      { sourceName: "n_sites", name: "nSites" },
      { sourceName: "n_hets", name: "nHets" },
      { sourceName: "n50_hets", name: "n50Hets" },
      { sourceName: "bdev", name: "bdev" },
      { sourceName: "bdev_se", name: "bdevSe" },
      { sourceName: "rel_cov", name: "relCov" },
      { sourceName: "rel_cov_se", name: "relCovSe" },
      { sourceName: "lod_lrr_baf", name: "lodLrrBaf" },
      { sourceName: "lod_baf_phase", name: "lodBafPhase" },
      { sourceName: "n_flips", name: "nFlips" },
      { sourceName: "baf_conc", name: "bafConc" },
      { sourceName: "lod_baf_conc", name: "lodBafConc" },
      { sourceName: "type_FINAL", name: "type" },
      { sourceName: "cf_FINAL", name: "cf" },
      //{ sourceName: "call_rate", name: "callRate" },
      //{ sourceName: "baf_auto", name: "bafAuto" },
    ],
  },
  {
    sourcePath: "data/biovu/BioVU_mloy_clean_02052025.txt",
    table: "sample",
    description: "BioVU blood mLOY",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "BioVU_blood_mLOY" },
      { sourceName: "sample_id", name: "sampleId" },
      { sourceName: "computed_gender", name: "computedGender" },
      { sourceName: "chrom", name: "chromosome", formatter: chromosomeFormatter() },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
      { sourceName: "length", name: "length" },
      { sourceName: "p_arm", name: "pArm" },
      { sourceName: "q_arm", name: "qArm" },
      { sourceName: "n_sites", name: "nSites" },
      { sourceName: "n_hets", name: "nHets" },
      { sourceName: "n50_hets", name: "n50Hets" },
      { sourceName: "bdev", name: "bdev" },
      { sourceName: "bdev_se", name: "bdevSe" },
      { sourceName: "rel_cov", name: "relCov" },
      { sourceName: "rel_cov_se", name: "relCovSe" },
      { sourceName: "lod_lrr_baf", name: "lodLrrBaf" },
      { sourceName: "lod_baf_phase", name: "lodBafPhase" },
      { sourceName: "n_flips", name: "nFlips" },
      { sourceName: "baf_conc", name: "bafConc" },
      { sourceName: "lod_baf_conc", name: "lodBafConc" },
      { sourceName: "type_FINAL", name: "type" },
      { sourceName: "cf_FINAL", name: "cf" },
    //  { sourceName: "call_rate", name: "callRate" },
    //  { sourceName: "baf_auto", name: "bafAuto" },
    ],
  },
  {
    sourcePath: "data/biovu/BioVU_denominator_clean_02052025.txt",
    table: "sample",
    description: "BioVU denominator",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "BioVU_denominator" },
      { sourceName: "Sample_ID", name: "sampleId" },
      { sourceName: "age", name: "age" },
      { sourceName: "sex", name: "sex" },
      { sourceName: "smoke_NFC", name: "smokeNFC" },
      { sourceName: "NumSNPs", name: "numSNPs" },
      { sourceName: "GD1", name: "GD1" },
      { sourceName: "GD2", name: "GD2" },
      { sourceName: "GD3", name: "GD3" },
      { sourceName: "GD4", name: "GD4" },
      { sourceName: "Percent_f", name: "PercentF" },
      { sourceName: "Percent_e", name: "PercentE" },
      { sourceName: "Percent_a", name: "PercentA" },
      { sourceName: "PopID", name: "PopID" },
      { sourceName: "dna_source", name: "dnaSource" },
      { sourceName: "array", name: "array" },
      { sourceName: "prior_cancer", name: "priorCancer" },
      { sourceName: "incident_cancer_hem", name: "incidentCancerHem" },
      { sourceName: "incident_cancer_myeloid", name: "incidentCancerMyeloid" },
      { sourceName: "incident_cancer_lymphoid", name: "incidentCancerLymphoid" },
      //{ sourceName: "cf_FINAL", name: "cf" },
     /// { sourceName: "call_rate", name: "callRate" },
     // { sourceName: "baf_auto", name: "bafAuto" },
     // { sourceName: "beg_GRCh38", name: "beginGrch38" },
     // { sourceName: "end_GRCh38", name: "endGrch38" },
    ],
  },
  {
    sourcePath: "data/topmed/topmed_automca_06112026.csv",
    table: "sample",
    description: "TOPMed autosomal mCAs",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "TOPMed_autosomal_mCAs" },
      { sourceName: "NWDID", name: "sampleId" },
      { sourceName: "chrom", name: "chromosome", formatter: chromosomeFormatter() },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
      { sourceName: "type", name: "type" },
      { sourceName: "cf", name: "cf" },
    ],
  },
  {
    sourcePath: "data/topmed/topmed_mlox_06112026.csv",
    table: "sample",
    description: "TOPMed mLOX",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "TOPMed_mLOX" },
      { sourceName: "NWDID", name: "sampleId" },
      { sourceName: "chrom", name: "chromosome", formatter: chromosomeFormatter() },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
      { sourceName: "type", name: "type" },
      { sourceName: "cf", name: "cf" },
    ],
  },
  {
    sourcePath: "data/topmed/topmed_mloy_06112026.csv",
    table: "sample",
    description: "TOPMed mLOY",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "TOPMed_mLOY" },
      { sourceName: "NWDID", name: "sampleId" },
      { sourceName: "chrom", name: "chromosome", formatter: chromosomeFormatter() },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
      { sourceName: null, name: "type", defaultValue: "Loss" },
      { sourceName: "cf", name: "cf" },
    ],
  },
  {
    sourcePath: "data/topmed/topmed_denom_0721026.csv",
    table: "sample",
    description: "TOPMed denominator",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "TOPMed_denominator" },
      { sourceName: "sample_id", name: "sampleId" },
      { sourceName: "age", name: "age" },
      { sourceName: "sex", name: "sex" },
      { sourceName: "dna_source", name: "dnaSource" },
      { sourceName: "Percent_f", name: "PercentF" },
      { sourceName: "Percent_e", name: "PercentE" },
      { sourceName: "Percent_a", name: "PercentA" },
      { sourceName: "PopID", name: "PopID" },
      { sourceName: "array", name: "array" },
      { sourceName: "Smoke", name: "smokeNFC", formatter: platformFormatter(topmedSmokeMap) },
    ],
  },
  {
    sourcePath: "data/jap/BBJ_autosomalevents_v2.csv",
    table: "sample",
    description: "JAP BBJ autosomal mCAs",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "JAP_BBJ_autosomal_mCAs" },
      { sourceName: "sample_id", name: "sampleId" },
      { sourceName: "computed_gender", name: "computedGender" },
      { sourceName: "chrom", name: "chromosome", formatter: chromosomeFormatter() },
      { sourceName: "beg_GRCH38", name: "beginGrch38" },
      { sourceName: "end_GRCH38", name: "endGrch38" },
      { sourceName: "length", name: "length" },
      { sourceName: "bdev", name: "bdev" },
      { sourceName: "bdev_se", name: "bdevSe" },
      { sourceName: "rel_cov", name: "relCov" },
      { sourceName: "rel_cov_se", name: "relCovSe" },
      { sourceName: "type", name: "type" },
      { sourceName: "cf", name: "cf" },
    ],
  },
  {
    sourcePath: "data/jap/BBJ_denom.csv",
    table: "sample",
    description: "JAP BBJ denominator",
    parseConfig: { bom: true },
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "JAP_BBJ_denominator" },
      { sourceName: "sample_id", name: "sampleId" },
      { sourceName: "age", name: "ageRange" },
      { sourceName: "age", name: "ageMin", formatter: ageRangeMinFormatter() },
      { sourceName: "age", name: "ageMax", formatter: ageRangeMaxFormatter() },
      { sourceName: "sex", name: "sex" },
      { sourceName: "dna_source", name: "dnaSource" },
      { sourceName: "Percent_f", name: "PercentF" },
      { sourceName: "Percent_e", name: "PercentE" },
      { sourceName: "Percent_a", name: "PercentA" },
      { sourceName: "PopID", name: "PopID" },
      { sourceName: "array", name: "array", formatter: platformFormatter(platformMap) },
      { sourceName: "prior_cancer", name: "priorCancer" },
    ],
  },
  {
    sourcePath: "data/iorra/IORRA_autosomal_events.csv",
    table: "sample",
    description: "IORRA autosomal mCAs",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "IORRA_autosomal_mCAs" },
      { sourceName: "sample_id", name: "sampleId" },
      { sourceName: "computed_gender", name: "computedGender" },
      { sourceName: "chrom", name: "chromosome", formatter: chromosomeFormatter() },
      { sourceName: "beg_GRCH38", name: "beginGrch38" },
      { sourceName: "end_GrCH38", name: "endGrch38" },
      { sourceName: "length", name: "length" },
      { sourceName: "p_arm", name: "pArm" },
      { sourceName: "q_arm", name: "qArm" },
      { sourceName: "n_sites", name: "nSites" },
      { sourceName: "n_hets", name: "nHets" },
      { sourceName: "n50_hets", name: "n50Hets" },
      { sourceName: "bdev", name: "bdev" },
      { sourceName: "bdev_se", name: "bdevSe" },
      { sourceName: "rel_cov", name: "relCov" },
      { sourceName: "rel_cov_se", name: "relCovSe" },
      { sourceName: "lod_lrr_baf", name: "lodLrrBaf" },
      { sourceName: "lod_baf_phase", name: "lodBafPhase" },
      { sourceName: "n_flips", name: "nFlips" },
      { sourceName: "baf_conc", name: "bafConc" },
      { sourceName: "lod_baf_conc", name: "lodBafConc" },
      { sourceName: "type", name: "type" },
      { sourceName: "cf", name: "cf" },
    ],
  },
  {
    sourcePath: "data/iorra/IORRA_denom.csv",
    table: "sample",
    description: "IORRA denominator",
    parseConfig: { bom: true },
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "IORRA_denominator" },
      { sourceName: "sample_id", name: "sampleId" },
      { sourceName: "age", name: "age" },
      { sourceName: "sex", name: "sex" },
      { sourceName: "dna_source", name: "dnaSource" },
      { sourceName: "Percent_f", name: "PercentF" },
      { sourceName: "Percent_e", name: "PercentE" },
      { sourceName: "Percent_a", name: "PercentA" },
      { sourceName: "PopID", name: "PopID" },
      { sourceName: "array", name: "array" },
    ],
  },
  {
    sourcePath: "data/iorra/IORRA_mLOX.txt",
    table: "sample",
    description: "IORRA mLOX",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "IORRA_mLOX" },
      { sourceName: "sample_id", name: "sampleId" },
      { sourceName: "computed_gender", name: "computedGender" },
      { sourceName: "chrom", name: "chromosome", formatter: chromosomeFormatter() },
      { sourceName: "beg_GRCH38", name: "beginGrch38" },
      { sourceName: "end_GrCH38", name: "endGrch38" },
      { sourceName: "length", name: "length" },
      { sourceName: "p_arm", name: "pArm" },
      { sourceName: "q_arm", name: "qArm" },
      { sourceName: "n_sites", name: "nSites" },
      { sourceName: "n_hets", name: "nHets" },
      { sourceName: "n50_hets", name: "n50Hets" },
      { sourceName: "bdev", name: "bdev" },
      { sourceName: "bdev_se", name: "bdevSe" },
      { sourceName: "rel_cov", name: "relCov" },
      { sourceName: "rel_cov_se", name: "relCovSe" },
      { sourceName: "lod_lrr_baf", name: "lodLrrBaf" },
      { sourceName: "lod_baf_phase", name: "lodBafPhase" },
      { sourceName: "n_flips", name: "nFlips" },
      { sourceName: "baf_conc", name: "bafConc" },
      { sourceName: "lod_baf_conc", name: "lodBafConc" },
      { sourceName: "type_FINAL", name: "type" },
      { sourceName: "cf_FINAL", name: "cf" },
    ],
  },
  {
    sourcePath: "data/iorra/IORRA_mLOY_events.csv",
    table: "sample",
    description: "IORRA mLOY",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "IORRA_mLOY" },
      { sourceName: "sample_id", name: "sampleId" },
      { sourceName: "computed_gender", name: "computedGender" },
      { sourceName: "chrom", name: "chromosome", formatter: chromosomeFormatter() },
      { sourceName: "beg_GRCH38", name: "beginGrch38" },
      { sourceName: "end_GrCH38", name: "endGrch38" },
      { sourceName: "length", name: "length" },
      { sourceName: "p_arm", name: "pArm" },
      { sourceName: "q_arm", name: "qArm" },
      { sourceName: "n_sites", name: "nSites" },
      { sourceName: "n_hets", name: "nHets" },
      { sourceName: "n50_hets", name: "n50Hets" },
      { sourceName: "bdev", name: "bdev" },
      { sourceName: "bdev_se", name: "bdevSe" },
      { sourceName: "rel_cov", name: "relCov" },
      { sourceName: "rel_cov_se", name: "relCovSe" },
      { sourceName: "lod_lrr_baf", name: "lodLrrBaf" },
      { sourceName: "lod_baf_phase", name: "lodBafPhase" },
      { sourceName: "n_flips", name: "nFlips" },
      { sourceName: "baf_conc", name: "bafConc" },
      { sourceName: "lod_baf_conc", name: "lodBafConc" },
      { sourceName: "type_FINAL", name: "type" },
      { sourceName: "cf_FINAL", name: "cf" },
    ],
  },
  {
    sourcePath: "data/estBB/mCA_events_EstBB_for_mCA_Explorer.txt",
    table: "sample",
    description: "EstBB mCA Explorer events",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "EstBB_mCA_Explorer_events" },
      { sourceName: "chrom", name: "chromosome", formatter: chromosomeFormatter() },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
      { sourceName: "length", name: "length" },
      { sourceName: "type", name: "type" },
      { sourceName: "cf", name: "cf" },
    ],
  }
];

export default sources;
