import { booleanFormatter } from "./services/formatters.js";

//update ukbb demominator and plco denominator for the new data version v3
export const sources = [
  {
    sourcePath: "data/UKBB_PLCO_V3/UKBB_denominator_92005app_clean.txt",
    table: "sample",
    description: "UKBB denominator",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "UKBB_denominator" },
      { sourceName: "Sample_ID", name: "sampleId" },
      { sourceName: "age", name: "age" },
      { sourceName: "sex", name: "sex" },
      { sourceName: "smoke_NFC", name: "smokeNFC" },
      { sourceName: "NumSNPs", name: "numSNPs" },
      { sourceName: "GD1", name: "GD1" },
      { sourceName: "GD2", name: "GD2" },
      { sourceName: "GD3", name: "GD3" },
      { sourceName: "GD4", name: "GD4" },
      { sourceName: "Percent_f", name: "PercentF" },
      { sourceName: "Percent_e", name: "PercentE" },
      { sourceName: "Percent_a", name: "PercentA" },
      { sourceName: "PopID", name: "PopID" },
      { sourceName: "dna_source", name: "dnaSource" },
      { sourceName: "array", name: "array" },
      { sourceName: "prior_cancer", name: "priorCancer" },
      { sourceName: "incident_cancer_hem", name: "incidentCancerHem" },
      { sourceName: "incident_cancer_myeloid", name: "incidentCancerMyeloid" },
      { sourceName: "incident_cancer_lymphoid", name: "incidentCancerLymphoid" },
      { sourceName: "cf_FINAL", name: "cf" },
      { sourceName: "call_rate", name: "callRate" },
      { sourceName: "baf_auto", name: "bafAuto" },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
    ],
  },
  {
    sourcePath: "data/UKBB_PLCO_V3/PLCO_denominator_clean.txt",
    table: "sample",
    description: "UKBB denominator",
    columns: [
      { sourceName: null, name: "dataset", defaultValue: "PLCO_denominator" },
      { sourceName: "Sample_ID", name: "sampleId" },
      { sourceName: "age", name: "age" },
      { sourceName: "sex", name: "sex" },
      { sourceName: "smoke_NFC", name: "smokeNFC" },
      { sourceName: "NumSNPs", name: "numSNPs" },
      { sourceName: "GD1", name: "GD1" },
      { sourceName: "GD2", name: "GD2" },
      { sourceName: "GD3", name: "GD3" },
      { sourceName: "GD4", name: "GD4" },
      { sourceName: "Percent_f", name: "PercentF" },
      { sourceName: "Percent_e", name: "PercentE" },
      { sourceName: "Percent_a", name: "PercentA" },
      { sourceName: "PopID", name: "PopID" },
      { sourceName: "dna_source", name: "dnaSource" },
      { sourceName: "array", name: "array" },
      { sourceName: "prior_cancer", name: "priorCancer" },
      { sourceName: "incident_cancer_hem", name: "incidentCancerHem" },
      { sourceName: "incident_cancer_myeloid", name: "incidentCancerMyeloid" },
      { sourceName: "incident_cancer_lymphoid", name: "incidentCancerLymphoid" },
      { sourceName: "cf_FINAL", name: "cf" },
      { sourceName: "call_rate", name: "callRate" },
      { sourceName: "baf_auto", name: "bafAuto" },
      { sourceName: "beg_GRCh38", name: "beginGrch38" },
      { sourceName: "end_GRCh38", name: "endGrch38" },
    ],
  },
];

export default sources;
